## LA Metro API

Do all of the imports and initialize variables

In [16]:
from la_metro import LAMetro
import pandas as pd
import datetime
import timeit
import time
import numpy as np

client = LAMetro()

template_df = pd.DataFrame(columns = ['grouped time', 'actual time', 'last report', 'id', 'route', 'latitude', 'longitude', 'run'])

df = template_df #restore df

count = 0

df

Empty DataFrame
Columns: [grouped time, actual time, last report, id, route, latitude, longitude, run]
Index: []

I will begin to grab the data

Here are things to note:
    - A timer is created at the beginning to time the function
    
    - I create a temp_df which will hold all of the bus data
    
    - I set a secondary timer to run the while loop for whatever duration I choose
    
    - The while loop begins
    
    - I will try to get all of the bus data from the API, but if it doesn't I except with
      an empty list
      
    - Then I get the current time (which will make it easier to visualize),
      so I won't have to track every bus and update them accordingly
    
    - I grab the data with a try and except for most variables
    
    - Create a tuple from the data and append it to the temp_df
    
    - Once the time is up, then I append the temp_df to the regular df
    
    - I stop the timer and print the duration
    
    - I show what is being held in the df

In [17]:
temp_df = template_df

#Your statements here

t_end = time.time() + (60 * 60 * 9) # <--- seconds * minutes * hours

print ("This will end at: ", time.asctime( time.localtime(t_end) ))

count = 0

while time.time() < t_end:
    
    print(len(temp_df))
    
    count = count + 1
    print('\n', "count: ", count)
    
    try:
        all_buses = client.bus.vehicles.all()
        print('\n', "num buses: ", len(all_buses))
    except:
        all_buses = []
        print('\n', "error")
    
    group_time = datetime.datetime.now()
    for bus in all_buses: #if error, then this loop will skip
        
        try:
            last_report = bus.seconds_since_report
        except:
            last_report = np.nan
        
        try:
            bus_id = bus.id
        except:
            bus_id = np.nan
        
        try:
            route = bus.route
        except:
            route = np.nan
        
        try:
            latitude = bus.latitude
        except:
            latitude = np.nan
        
        try:
            longitude = bus.longitude
        except:
            longitude = np.nan
        
        try:
            run = bus.run.name
        except:
            run = "none"
        
        new_bus = {'grouped time': group_time,
                   'actual time' : datetime.datetime.now(),
                   'last report' : last_report,
                   'id' : bus_id,
                   'route' : route,
                   'latitude' : latitude,
                   'longitude' : longitude,
                   'run' : run}
                   
                   
        #append row to the dataframe
        temp_df = temp_df.append(new_bus, ignore_index=True)
        
df = df.append(temp_df, ignore_index = True)

print("num iterations: ", count)

df

This will end at:  Wed Jul 22 18:44:26 2020
0

 count:  1

 num buses:  807
807

 count:  2

 num buses:  798
1605

 count:  3

 num buses:  807
2412

 count:  4

 num buses:  807
3219

 count:  5

 num buses:  800
4019

 count:  6

 num buses:  797
4816

 count:  7

 num buses:  811
5627

 count:  8

 num buses:  814
6441

 count:  9

 num buses:  0
6441

 count:  10

 num buses:  0
6441

 count:  11

 num buses:  0
6441

 count:  12

 num buses:  0
6441

 count:  13

 num buses:  0
6441

 count:  14

 num buses:  0
6441

 count:  15

 num buses:  0
6441

 count:  16

 num buses:  0
6441

 count:  17

 num buses:  0
6441

 count:  18

 num buses:  0
6441

 count:  19

 num buses:  0
6441

 count:  20

 num buses:  0
6441

 count:  21

 num buses:  0
6441

 count:  22

 num buses:  0
6441

 count:  23

 num buses:  0
6441

 count:  24

 num buses:  0
6441

 count:  25

 num buses:  0
6441

 count:  26

 num buses:  0
6441

 count:  27

 num buses:  0
6441

 count:  28

 num buses:  0
6441

 count:  29

 num buses:  0
6441

 count:  30

 num buses:  0
6441

 count:  31

 num buses:  0
6441

 count:  32

 num buses:  0
6441

 count:  33

 num buses:  0
6441

 count:  34

 num buses:  0
6441

 count:  35

 num buses:  0
6441

 count:  36

 num buses:  0
6441

 count:  37

 num buses:  0
6441

 count:  38

 num buses:  0
6441

 count:  39

 num buses:  0
6441

 count:  40

 num buses:  0
6441

 count:  41

 num buses:  0
6441

 count:  42

 num buses:  0
6441

 count:  43

 num buses:  0
6441

 count:  44

 num buses:  0
6441

 count:  45

 num buses:  0
6441

 count:  46

 num buses:  0
6441

 count:  47

 num buses:  0
6441

 count:  48

 num buses:  0
6441

 count:  49

 num buses:  0
6441

 count:  50

 num buses:  0
6441

 count:  51

 num buses:  0
6441

 count:  52

 num buses:  0
6441

 count:  53

 num buses:  0
6441

 count:  54

 num buses:  0
6441

 count:  55

 num buses:  0
6441

 count:  56

 num buses:  0
6441

 count:  57

 num buses:  0
6441

 count:  58

 num buses:  0
6441

 count:  59

 num buses:  0
6441

 count:  60

 num buses:  0
6441

 count:  61

 num buses:  0
6441

 count:  62

 num buses:  0
6441

 count:  63

 num buses:  0
6441

 count:  64

 num buses:  0
6441

 count:  65

 num buses:  0
6441

 count:  66

 num buses:  0
6441

 count:  67

 num buses:  0
6441

 count:  68

 num buses:  0
6441

 count:  69

 num buses:  0
6441

 count:  70

 num buses:  806
7247

 count:  71

 num buses:  811
8058

 count:  72

 num buses:  794
8852

 count:  73

 num buses:  814
9666

 count:  74

 num buses:  809
10475

 count:  75

 num buses:  814
11289

 count:  76

 num buses:  812
12101

 count:  77

 num buses:  817
12918

 count:  78

 num buses:  818
13736

 count:  79

 num buses:  830
14566

 count:  80

 num buses:  835
15401

 count:  81

 num buses:  831
16232

 count:  82

 num buses:  827
17059

 count:  83

 num buses:  833
17892

 count:  84

 num buses:  820
18712

 count:  85

 num buses:  832
19544

 count:  86

 num buses:  840
20384

 count:  87

 num buses:  849
21233

 count:  88

 num buses:  840
22073

 count:  89

 num buses:  857
22930

 count:  90

 num buses:  865
23795

 count:  91

 num buses:  858
24653

 count:  92

 num buses:  847
25500

 count:  93

 num buses:  862
26362

 count:  94

 num buses:  0
26362

 count:  95

 num buses:  0
26362

 count:  96

 num buses:  0
26362

 count:  97

 num buses:  0
26362

 count:  98

 num buses:  0
26362

 count:  99

 num buses:  0
26362

 count:  100

 num buses:  0
26362

 count:  101

 num buses:  0
26362

 count:  102

 num buses:  0
26362

 count:  103

 num buses:  0
26362

 count:  104

 num buses:  0
26362

 count:  105

 num buses:  0
26362

 count:  106

 num buses:  0
26362

 count:  107

 num buses:  0
26362

 count:  108

 num buses:  0
26362

 count:  109

 num buses:  0
26362

 count:  110

 num buses:  0
26362

 count:  111

 num buses:  0
26362

 count:  112

 num buses:  0
26362

 count:  113

 num buses:  0
26362

 count:  114

 num buses:  0
26362

 count:  115

 num buses:  0
26362

 count:  116

 num buses:  0
26362

 count:  117

 num buses:  0
26362

 count:  118

 num buses:  0
26362

 count:  119

 num buses:  0
26362

 count:  120

 num buses:  0
26362

 count:  121

 num buses:  857
27219

 count:  122

 num buses:  872
28091

 count:  123

 num buses:  867
28958

 count:  124

 num buses:  863
29821

 count:  125

 num buses:  868
30689

 count:  126

 num buses:  0
30689

 count:  127

 num buses:  0
30689

 count:  128

 num buses:  0
30689

 count:  129

 num buses:  0
30689

 count:  130

 num buses:  0
30689

 count:  131

 num buses:  0
30689

 count:  132

 num buses:  0
30689

 count:  133

 num buses:  0
30689

 count:  134

 num buses:  0
30689

 count:  135

 num buses:  0
30689

 count:  136

 num buses:  0
30689

 count:  137

 num buses:  0
30689

 count:  138

 num buses:  0
30689

 count:  139

 num buses:  0
30689

 count:  140

 num buses:  0
30689

 count:  141

 num buses:  0
30689

 count:  142

 num buses:  0
30689

 count:  143

 num buses:  0
30689

 count:  144

 num buses:  0
30689

 count:  145

 num buses:  0
30689

 count:  146

 num buses:  0
30689

 count:  147

 num buses:  0
30689

 count:  148

 num buses:  0
30689

 count:  149

 num buses:  893
31582

 count:  150

 num buses:  874
32456

 count:  151

 num buses:  880
33336

 count:  152

 num buses:  891
34227

 count:  153

 num buses:  882
35109

 count:  154

 num buses:  880
35989

 count:  155

 num buses:  869
36858

 count:  156

 num buses:  883
37741

 count:  157

 num buses:  895
38636

 count:  158

 num buses:  893
39529

 count:  159

 num buses:  882
40411

 count:  160

 num buses:  888
41299

 count:  161

 num buses:  894
42193

 count:  162

 num buses:  909
43102

 count:  163

 num buses:  882
43984

 count:  164

 num buses:  898
44882

 count:  165

 num buses:  907
45789

 count:  166

 num buses:  885
46674

 count:  167

 num buses:  892
47566

 count:  168

 num buses:  911
48477

 count:  169

 num buses:  897
49374

 count:  170

 num buses:  897
50271

 count:  171

 num buses:  898
51169

 count:  172

 num buses:  896
52065

 count:  173

 num buses:  913
52978

 count:  174

 num buses:  899
53877

 count:  175

 num buses:  889
54766

 count:  176

 num buses:  0
54766

 count:  177

 num buses:  0
54766

 count:  178

 num buses:  0
54766

 count:  179

 num buses:  0
54766

 count:  180

 num buses:  0
54766

 count:  181

 num buses:  0
54766

 count:  182

 num buses:  0
54766

 count:  183

 num buses:  0
54766

 count:  184

 num buses:  0
54766

 count:  185

 num buses:  0
54766

 count:  186

 num buses:  0
54766

 count:  187

 num buses:  0
54766

 count:  188

 num buses:  0
54766

 count:  189

 num buses:  0
54766

 count:  190

 num buses:  0
54766

 count:  191

 num buses:  0
54766

 count:  192

 num buses:  0
54766

 count:  193

 num buses:  0
54766

 count:  194

 num buses:  0
54766

 count:  195

 num buses:  0
54766

 count:  196

 num buses:  0
54766

 count:  197

 num buses:  0
54766

 count:  198

 num buses:  0
54766

 count:  199

 num buses:  0
54766

 count:  200

 num buses:  0
54766

 count:  201

 num buses:  0
54766

 count:  202

 num buses:  0
54766

 count:  203

 num buses:  0
54766

 count:  204

 num buses:  0
54766

 count:  205

 num buses:  0
54766

 count:  206

 num buses:  0
54766

 count:  207

 num buses:  0
54766

 count:  208

 num buses:  0
54766

 count:  209

 num buses:  0
54766

 count:  210

 num buses:  0
54766

 count:  211

 num buses:  0
54766

 count:  212

 num buses:  0
54766

 count:  213

 num buses:  0
54766

 count:  214

 num buses:  0
54766

 count:  215

 num buses:  0
54766

 count:  216

 num buses:  0
54766

 count:  217

 num buses:  0
54766

 count:  218

 num buses:  0
54766

 count:  219

 num buses:  0
54766

 count:  220

 num buses:  0
54766

 count:  221

 num buses:  0
54766

 count:  222

 num buses:  0
54766

 count:  223

 num buses:  0
54766

 count:  224

 num buses:  0
54766

 count:  225

 num buses:  0
54766

 count:  226

 num buses:  0
54766

 count:  227

 num buses:  0
54766

 count:  228

 num buses:  0
54766

 count:  229

 num buses:  0
54766

 count:  230

 num buses:  0
54766

 count:  231

 num buses:  0
54766

 count:  232

 num buses:  0
54766

 count:  233

 num buses:  0
54766

 count:  234

 num buses:  0
54766

 count:  235

 num buses:  0
54766

 count:  236

 num buses:  0
54766

 count:  237

 num buses:  0
54766

 count:  238

 num buses:  0
54766

 count:  239

 num buses:  0
54766

 count:  240

 num buses:  0
54766

 count:  241

 num buses:  0
54766

 count:  242

 num buses:  0
54766

 count:  243

 num buses:  0
54766

 count:  244

 num buses:  0
54766

 count:  245

 num buses:  0
54766

 count:  246

 num buses:  0
54766

 count:  247

 num buses:  0
54766

 count:  248

 num buses:  0
54766

 count:  249

 num buses:  0
54766

 count:  250

 num buses:  0
54766

 count:  251

 num buses:  0
54766

 count:  252

 num buses:  0
54766

 count:  253

 num buses:  906
55672

 count:  254

 num buses:  903
56575

 count:  255

 num buses:  903
57478

 count:  256

 num buses:  910
58388

 count:  257

 num buses:  924
59312

 count:  258

 num buses:  0
59312

 count:  259

 num buses:  0
59312

 count:  260

 num buses:  0
59312

 count:  261

 num buses:  0
59312

 count:  262

 num buses:  0
59312

 count:  263

 num buses:  0
59312

 count:  264

 num buses:  0
59312

 count:  265

 num buses:  0
59312

 count:  266

 num buses:  0
59312

 count:  267

 num buses:  0
59312

 count:  268

 num buses:  0
59312

 count:  269

 num buses:  0
59312

 count:  270

 num buses:  0
59312

 count:  271

 num buses:  0
59312

 count:  272

 num buses:  0
59312

 count:  273

 num buses:  0
59312

 count:  274

 num buses:  0
59312

 count:  275

 num buses:  0
59312

 count:  276

 num buses:  0
59312

 count:  277

 num buses:  0
59312

 count:  278

 num buses:  0
59312

 count:  279

 num buses:  0
59312

 count:  280

 num buses:  0
59312

 count:  281

 num buses:  0
59312

 count:  282

 num buses:  0
59312

 count:  283

 num buses:  0
59312

 count:  284

 num buses:  0
59312

 count:  285

 num buses:  0
59312

 count:  286

 num buses:  0
59312

 count:  287

 num buses:  0
59312

 count:  288

 num buses:  0
59312

 count:  289

 num buses:  0
59312

 count:  290

 num buses:  0
59312

 count:  291

 num buses:  0
59312

 count:  292

 num buses:  0
59312

 count:  293

 num buses:  0
59312

 count:  294

 num buses:  0
59312

 count:  295

 num buses:  0
59312

 count:  296

 num buses:  0
59312

 count:  297

 num buses:  0
59312

 count:  298

 num buses:  0
59312

 count:  299

 num buses:  0
59312

 count:  300

 num buses:  0
59312

 count:  301

 num buses:  0
59312

 count:  302

 num buses:  0
59312

 count:  303

 num buses:  0
59312

 count:  304

 num buses:  0
59312

 count:  305

 num buses:  0
59312

 count:  306

 num buses:  0
59312

 count:  307

 num buses:  0
59312

 count:  308

 num buses:  921
60233

 count:  309

 num buses:  935
61168

 count:  310

 num buses:  923
62091

 count:  311

 num buses:  918
63009

 count:  312

 num buses:  930
63939

 count:  313

 num buses:  936
64875

 count:  314

 num buses:  962
65837

 count:  315

 num buses:  976
66813

 count:  316

 num buses:  962
67775

 count:  317

 num buses:  0
67775

 count:  318

 num buses:  0
67775

 count:  319

 num buses:  0
67775

 count:  320

 num buses:  0
67775

 count:  321

 num buses:  0
67775

 count:  322

 num buses:  0
67775

 count:  323

 num buses:  0
67775

 count:  324

 num buses:  0
67775

 count:  325

 num buses:  0
67775

 count:  326

 num buses:  0
67775

 count:  327

 num buses:  967
68742

 count:  328

 num buses:  973
69715

 count:  329

 num buses:  968
70683

 count:  330

 num buses:  972
71655

 count:  331

 num buses:  982
72637

 count:  332

 num buses:  0
72637

 count:  333

 num buses:  974
73611

 count:  334

 num buses:  985
74596

 count:  335

 num buses:  998
75594

 count:  336

 num buses:  979
76573

 count:  337

 num buses:  967
77540

 count:  338

 num buses:  980
78520

 count:  339

 num buses:  974
79494

 count:  340

 num buses:  0
79494

 count:  341

 num buses:  0
79494

 count:  342

 num buses:  0
79494

 count:  343

 num buses:  0
79494

 count:  344

 num buses:  0
79494

 count:  345

 num buses:  0
79494

 count:  346

 num buses:  0
79494

 count:  347

 num buses:  0
79494

 count:  348

 num buses:  0
79494

 count:  349

 num buses:  0
79494

 count:  350

 num buses:  0
79494

 count:  351

 num buses:  0
79494

 count:  352

 num buses:  0
79494

 count:  353

 num buses:  0
79494

 count:  354

 num buses:  0
79494

 count:  355

 num buses:  0
79494

 count:  356

 num buses:  0
79494

 count:  357

 num buses:  0
79494

 count:  358

 num buses:  0
79494

 count:  359

 num buses:  0
79494

 count:  360

 num buses:  0
79494

 count:  361

 num buses:  0
79494

 count:  362

 num buses:  0
79494

 count:  363

 num buses:  0
79494

 count:  364

 num buses:  0
79494

 count:  365

 num buses:  0
79494

 count:  366

 num buses:  0
79494

 count:  367

 num buses:  0
79494

 count:  368

 num buses:  0
79494

 count:  369

 num buses:  0
79494

 count:  370

 num buses:  0
79494

 count:  371

 num buses:  0
79494

 count:  372

 num buses:  0
79494

 count:  373

 num buses:  0
79494

 count:  374

 num buses:  0
79494

 count:  375

 num buses:  0
79494

 count:  376

 num buses:  0
79494

 count:  377

 num buses:  0
79494

 count:  378

 num buses:  0
79494

 count:  379

 num buses:  0
79494

 count:  380

 num buses:  0
79494

 count:  381

 num buses:  0
79494

 count:  382

 num buses:  0
79494

 count:  383

 num buses:  0
79494

 count:  384

 num buses:  0
79494

 count:  385

 num buses:  0
79494

 count:  386

 num buses:  0
79494

 count:  387

 num buses:  0
79494

 count:  388

 num buses:  0
79494

 count:  389

 num buses:  0
79494

 count:  390

 num buses:  0
79494

 count:  391

 num buses:  0
79494

 count:  392

 num buses:  0
79494

 count:  393

 num buses:  0
79494

 count:  394

 num buses:  0
79494

 count:  395

 num buses:  0
79494

 count:  396

 num buses:  0
79494

 count:  397

 num buses:  0
79494

 count:  398

 num buses:  0
79494

 count:  399

 num buses:  0
79494

 count:  400

 num buses:  0
79494

 count:  401

 num buses:  0
79494

 count:  402

 num buses:  0
79494

 count:  403

 num buses:  0
79494

 count:  404

 num buses:  953
80447

 count:  405

 num buses:  969
81416

 count:  406

 num buses:  963
82379

 count:  407

 num buses:  973
83352

 count:  408

 num buses:  964
84316

 count:  409

 num buses:  954
85270

 count:  410

 num buses:  929
86199

 count:  411

 num buses:  927
87126

 count:  412

 num buses:  920
88046

 count:  413

 num buses:  920
88966

 count:  414

 num buses:  0
88966

 count:  415

 num buses:  0
88966

 count:  416

 num buses:  0
88966

 count:  417

 num buses:  0
88966

 count:  418

 num buses:  0
88966

 count:  419

 num buses:  0
88966

 count:  420

 num buses:  0
88966

 count:  421

 num buses:  0
88966

 count:  422

 num buses:  0
88966

 count:  423

 num buses:  0
88966

 count:  424

 num buses:  0
88966

 count:  425

 num buses:  0
88966

 count:  426

 num buses:  0
88966

 count:  427

 num buses:  0
88966

 count:  428

 num buses:  0
88966

 count:  429

 num buses:  0
88966

 count:  430

 num buses:  0
88966

 count:  431

 num buses:  0
88966

 count:  432

 num buses:  0
88966

 count:  433

 num buses:  0
88966

 count:  434

 num buses:  0
88966

 count:  435

 num buses:  0
88966

 count:  436

 num buses:  0
88966

 count:  437

 num buses:  0
88966

 count:  438

 num buses:  0
88966

 count:  439

 num buses:  0
88966

 count:  440

 num buses:  0
88966

 count:  441

 num buses:  0
88966

 count:  442

 num buses:  0
88966

 count:  443

 num buses:  0
88966

 count:  444

 num buses:  0
88966

 count:  445

 num buses:  0
88966

 count:  446

 num buses:  0
88966

 count:  447

 num buses:  0
88966

 count:  448

 num buses:  0
88966

 count:  449

 num buses:  0
88966

 count:  450

 num buses:  0
88966

 count:  451

 num buses:  0
88966

 count:  452

 num buses:  0
88966

 count:  453

 num buses:  0
88966

 count:  454

 num buses:  0
88966

 count:  455

 num buses:  918
89884

 count:  456

 num buses:  888
90772

 count:  457

 num buses:  888
91660

 count:  458

 num buses:  876
92536

 count:  459

 num buses:  870
93406

 count:  460

 num buses:  855
94261

 count:  461

 num buses:  843
95104

 count:  462

 num buses:  818
95922

 count:  463

 num buses:  808
96730

 count:  464

 num buses:  814
97544

 count:  465

 num buses:  785
98329

 count:  466

 num buses:  779
99108

 count:  467

 num buses:  0
99108

 count:  468

 num buses:  0
99108

 count:  469

 num buses:  0
99108

 count:  470

 num buses:  0
99108

 count:  471

 num buses:  0
99108

 count:  472

 num buses:  0
99108

 count:  473

 num buses:  0
99108

 count:  474

 num buses:  0
99108

 count:  475

 num buses:  0
99108

 count:  476

 num buses:  0
99108

 count:  477

 num buses:  0
99108

 count:  478

 num buses:  0
99108

 count:  479

 num buses:  0
99108

 count:  480

 num buses:  0
99108

 count:  481

 num buses:  0
99108

 count:  482

 num buses:  0
99108

 count:  483

 num buses:  0
99108

 count:  484

 num buses:  0
99108

 count:  485

 num buses:  0
99108

 count:  486

 num buses:  0
99108

 count:  487

 num buses:  0
99108

 count:  488

 num buses:  0
99108

 count:  489

 num buses:  0
99108

 count:  490

 num buses:  0
99108

 count:  491

 num buses:  0
99108

 count:  492

 num buses:  0
99108

 count:  493

 num buses:  0
99108

 count:  494

 num buses:  0
99108

 count:  495

 num buses:  0
99108

 count:  496

 num buses:  0
99108

 count:  497

 num buses:  0
99108

 count:  498

 num buses:  0
99108

 count:  499

 num buses:  0
99108

 count:  500

 num buses:  0
99108

 count:  501

 num buses:  0
99108

 count:  502

 num buses:  0
99108

 count:  503

 num buses:  0
99108

 count:  504

 num buses:  0
99108

 count:  505

 num buses:  0
99108

 count:  506

 num buses:  0
99108

 count:  507

 num buses:  0
99108

 count:  508

 num buses:  0
99108

 count:  509

 num buses:  0
99108

 count:  510

 num buses:  0
99108

 count:  511

 num buses:  0
99108

 count:  512

 num buses:  0
99108

 count:  513

 num buses:  0
99108

 count:  514

 num buses:  0
99108

 count:  515

 num buses:  0
99108

 count:  516

 num buses:  0
99108

 count:  517

 num buses:  0
99108

 count:  518

 num buses:  0
99108

 count:  519

 num buses:  0
99108

 count:  520

 num buses:  0
99108

 count:  521

 num buses:  0
99108

 count:  522

 num buses:  0
99108

 count:  523

 num buses:  0
99108

 count:  524

 num buses:  0
99108

 count:  525

 num buses:  0
99108

 count:  526

 num buses:  0
99108

 count:  527

 num buses:  0
99108

 count:  528

 num buses:  0
99108

 count:  529

 num buses:  0
99108

 count:  530

 num buses:  0
99108

 count:  531

 num buses:  0
99108

 count:  532

 num buses:  0
99108

 count:  533

 num buses:  0
99108

 count:  534

 num buses:  0
99108

 count:  535

 num buses:  0
99108

 count:  536

 num buses:  0
99108

 count:  537

 num buses:  0
99108

 count:  538

 num buses:  770
99878

 count:  539

 num buses:  740
100618

 count:  540

 num buses:  753
num iterations:  540

,grouped time,actual time,last report,id,route,latitude,longitude,run
0,2020-07-22 09:44:26.430997,2020-07-22 09:44:26.634685,12,3129,607,33.971173,-118.362493,Clockwis to N. Inglewood Shuttle
1,2020-07-22 09:44:26.430997,2020-07-22 09:44:26.859215,65,8126,45,34.034275,-118.263405,South to San Pedro-Rosecrans
2,2020-07-22 09:44:26.430997,2020-07-22 09:44:27.070036,12,1600,794,34.163241,-118.284488,North to Sylmar Station
3,2020-07-22 09:44:26.430997,2020-07-22 09:44:27.257397,92,4140,71,34.063148,-118.168747,West to Downtown LA - Broadway-Venice
4,2020-07-22 09:44:26.430997,2020-07-22 09:44:27.454423,12,8641,117,33.943316,-118.246068,West to Lax City Bus Ctr
...,...,...,...,...,...,...,...,...
101366,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.623953,182,3945,14,34.076046,-118.359283,South to Washington/Fairfax Transit Hub
101367,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.900232,18,3997,94,34.223754,-118.375764,North to Sylmar Station
101368,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.200471,44,8592,166,34.249901,-118.606163,East to Sun Valley
101369,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.488402,44,1716,53,33.934093,-118.254295,South to Avalon Station
101370,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.768894,45,4135,4,34.077835,-118.262812,West to Santa Monica

The dftypes are below

In [94]:
df.dtypes

time           datetime64[ns]
last report            object
id                     object
route                  object
latitude              float64
longitude             float64
run                    object
dtype: object

Below are two different code blocks:
    1. The first one will create a new csv (headers and no index)
    2. The second will append to the csv (append mode, no headers, no index)

In [8]:
#Create new csv file

df.to_csv('LAMetro_bus_data.csv', header=True, index=False)

In [18]:
#Append to csv file

df.to_csv('LAMetro_bus_data.csv', mode='a', header=False, index=False)
print("Stored")

Stored