# LA Metro Bus Data Cleaning
I have data from the following days that need to be cleaned: 7/16, 7/17, 7/18, 7/20, 7/22

In [3]:
import pandas as pd

In [4]:
bus_df = pd.read_csv("../Bus Data/LAMetro_bus_data.csv")
bus_df

FileNotFoundError: [Errno 2] File ../Bus Data/LAMetro_bus_data.csv does not exist: '../Bus Data/LAMetro_bus_data.csv'

I need to change the grouped time and actual time to datetime format

In [27]:
bus_df["grouped time"] = bus_df["grouped time"].apply(pd.to_datetime)
bus_df["actual time"] = bus_df["actual time"].apply(pd.to_datetime)

In [28]:
bus_df.dtypes

grouped time    datetime64[ns]
actual time     datetime64[ns]
last report              int64
id                       int64
route                  float64
latitude               float64
longitude              float64
run                     object
dtype: object

I am also going to make an hour column

In [42]:
bus_df["hour"] = bus_df["actual time"].map(lambda x: x.hour)
bus_df

,grouped time,actual time,last report,id,route,latitude,longitude,run,hour,direction,day
0,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.605064,8,1600,794.0,34.033451,-118.264847,North to Sylmar Station,8,North,2020-07-16
1,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.786010,8,4140,268.0,34.148680,-118.080071,South to El Monte Station,8,South,2020-07-16
2,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.957790,8,4171,70.0,34.052975,-118.249674,East to El Monte Station,8,East,2020-07-16
3,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.153969,125,4061,705.0,34.003990,-118.227187,North to West Hollywood,8,North,2020-07-16
4,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.334927,37,9567,108.0,33.972591,-118.113319,West to Marina Del Rey,8,West,2020-07-16
...,...,...,...,...,...,...,...,...,...,...,...
499872,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.623953,182,3945,14.0,34.076046,-118.359283,South to Washington/Fairfax Transit Hub,18,South,2020-07-22
499873,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.900232,18,3997,94.0,34.223754,-118.375764,North to Sylmar Station,18,North,2020-07-22
499874,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.200471,44,8592,166.0,34.249901,-118.606163,East to Sun Valley,18,East,2020-07-22
499875,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.488402,44,1716,53.0,33.934093,-118.254295,South to Avalon Station,18,South,2020-07-22
499876,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.768894,45,4135,4.0,34.077835,-118.262812,West to Santa Monica,18,West,2020-07-22

I will now split the direction from the run column and make it its own column

In [30]:
direction_df = bus_df["run"].str.split(' ', n = 1, expand = True)
direction_df.columns = ["direction", "name"]
bus_df["direction"] = direction_df["direction"]
bus_df

,grouped time,actual time,last report,id,route,latitude,longitude,run,hour,direction
0,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.605064,8,1600,794.0,34.033451,-118.264847,North to Sylmar Station,8,North
1,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.786010,8,4140,268.0,34.148680,-118.080071,South to El Monte Station,8,South
2,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.957790,8,4171,70.0,34.052975,-118.249674,East to El Monte Station,8,East
3,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.153969,125,4061,705.0,34.003990,-118.227187,North to West Hollywood,8,North
4,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.334927,37,9567,108.0,33.972591,-118.113319,West to Marina Del Rey,8,West
...,...,...,...,...,...,...,...,...,...,...
499872,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.623953,182,3945,14.0,34.076046,-118.359283,South to Washington/Fairfax Transit Hub,18,South
499873,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.900232,18,3997,94.0,34.223754,-118.375764,North to Sylmar Station,18,North
499874,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.200471,44,8592,166.0,34.249901,-118.606163,East to Sun Valley,18,East
499875,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.488402,44,1716,53.0,33.934093,-118.254295,South to Avalon Station,18,South
499876,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.768894,45,4135,4.0,34.077835,-118.262812,West to Santa Monica,18,West

Here I am going to split the day from the actual time and make it its own column

In [37]:
day_df = bus_df["actual time"].astype(str).str.split(' ', n = 1, expand = True)
day_df.columns = ["day", "time"]
bus_df["day"] = day_df["day"]
bus_df

,grouped time,actual time,last report,id,route,latitude,longitude,run,hour,direction,day
0,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.605064,8,1600,794.0,34.033451,-118.264847,North to Sylmar Station,8,North,2020-07-16
1,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.786010,8,4140,268.0,34.148680,-118.080071,South to El Monte Station,8,South,2020-07-16
2,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.957790,8,4171,70.0,34.052975,-118.249674,East to El Monte Station,8,East,2020-07-16
3,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.153969,125,4061,705.0,34.003990,-118.227187,North to West Hollywood,8,North,2020-07-16
4,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.334927,37,9567,108.0,33.972591,-118.113319,West to Marina Del Rey,8,West,2020-07-16
...,...,...,...,...,...,...,...,...,...,...,...
499872,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.623953,182,3945,14.0,34.076046,-118.359283,South to Washington/Fairfax Transit Hub,18,South,2020-07-22
499873,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.900232,18,3997,94.0,34.223754,-118.375764,North to Sylmar Station,18,North,2020-07-22
499874,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.200471,44,8592,166.0,34.249901,-118.606163,East to Sun Valley,18,East,2020-07-22
499875,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.488402,44,1716,53.0,33.934093,-118.254295,South to Avalon Station,18,South,2020-07-22
499876,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.768894,45,4135,4.0,34.077835,-118.262812,West to Santa Monica,18,West,2020-07-22

I am going to change all of the day values into their day of the week values

In [41]:
bus_df["day"].unique()

array(['2020-07-16', '2020-07-17', '2020-07-18', '2020-07-20',
       '2020-07-22'], dtype=object)

In [44]:
bus_df['day'] = bus_df['day'].map({'2020-07-16' : 'Thursday',
                                   '2020-07-17' : 'Friday',
                                   '2020-07-18' : 'Saturday',
                                   '2020-07-20' : 'Monday',
                                   '2020-07-22' : 'Wednesday'
                                  })
bus_df

,grouped time,actual time,last report,id,route,latitude,longitude,run,hour,direction,day
0,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.605064,8,1600,794.0,34.033451,-118.264847,North to Sylmar Station,8,North,Thursday
1,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.786010,8,4140,268.0,34.148680,-118.080071,South to El Monte Station,8,South,Thursday
2,2020-07-16 08:54:29.410523,2020-07-16 08:54:30.957790,8,4171,70.0,34.052975,-118.249674,East to El Monte Station,8,East,Thursday
3,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.153969,125,4061,705.0,34.003990,-118.227187,North to West Hollywood,8,North,Thursday
4,2020-07-16 08:54:29.410523,2020-07-16 08:54:31.334927,37,9567,108.0,33.972591,-118.113319,West to Marina Del Rey,8,West,Thursday
...,...,...,...,...,...,...,...,...,...,...,...
499872,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.623953,182,3945,14.0,34.076046,-118.359283,South to Washington/Fairfax Transit Hub,18,South,Wednesday
499873,2020-07-22 18:43:29.161669,2020-07-22 18:47:54.900232,18,3997,94.0,34.223754,-118.375764,North to Sylmar Station,18,North,Wednesday
499874,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.200471,44,8592,166.0,34.249901,-118.606163,East to Sun Valley,18,East,Wednesday
499875,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.488402,44,1716,53.0,33.934093,-118.254295,South to Avalon Station,18,South,Wednesday
499876,2020-07-22 18:43:29.161669,2020-07-22 18:47:55.768894,45,4135,4.0,34.077835,-118.262812,West to Santa Monica,18,West,Wednesday

In [45]:
bus_df.to_csv('[Cleaned] LA Metro Bus Data.csv', header=True, index=False)

Now the data is cleaned and has been exported to csv, so let's move to the EDA portion